### ISSUE TITLE
Provide functionality for parameter filtering

### ISSUE THREAD

**Issue by jorgenherje** [equinor/webviz#321]
When using ensemble parameters or a union of parameters across ensembles, the list can become large. Consider creating component/class/hook/utility functionality to be able to set some filtering criteria and provide a list of parameters fulfilling the filter selection for usage.

E.g. component to set based on wanted `EnsembleParameter` settings/attributes - see: https://github.com/equinor/webviz/blob/main/frontend/src/framework/EnsembleParameters.ts

Types:
* Filter of `Parameter` to create shorter list of parameter names to select
* Filter of `Parameter` to create a subset of realizations to look at

-----

Mentions:

* Hans' [comment](https://github.com/equinor/webviz/pull/320#pullrequestreview-1638447023) 
   * The parameter list will be overwhelming if you don't know what to look for. Not directly related to this PR but we need both filtering of parameters(e.g. based on group) and sorting of parameters on how "important" they are. We can do this by calculating the correlation of the parameter values to the timeseries at a given date. I think we could automate this by selecting the last date (automatically) and perform the correlation. There exists an early attempt of an endpoint on the api to do this correlation: https://github.com/equinor/webviz/blob/main/backend/src/backend/primary/routers/correlations/router.py
   
* My [comment](https://github.com/equinor/webviz/pull/320#issuecomment-1730912897):
   * Three types of parameter filtering?: 
      - Filtering based on criteria/attributes of [`Parameter`](https://github.com/equinor/webviz/blob/main/frontend/src/framework/EnsembleParameters.ts) type to provide a shorter list of  parameter names in e.g. a dropdown.
      - Filtering based on values of a `Parameter`, i.e. functionality as mentioned above here - providing a shorter list.
      - Filtering based on criteria which results in a subset of wanted realization numbers?

**Comment by HansKallekleiv** [comment]
Sounds like a good list.
Some comments on the last two:

>     * Filtering based on values of a `Parameter`, i.e. functionality as mentioned above here - providing a shorter list.
This is more a ranking/soring of the parameters based on how "important" or correlated they are.
It can also be used as filtering by removing parameters with little correlation.
This can also be visualized as done in the existing ParameterAnalysis plugin in webviz-subsurface.

![image](https://github.com/equinor/webviz/assets/16436291/c6370dbf-392d-40fe-b5c1-5cdd96610932)


>     * Filtering based on criteria which results in a subset of wanted realization numbers?
Yes. Filterting based on parameter values => Subset of realizations => Updated correlations
A relevant filter component is in the existing ParameterAnalysis plugin.
![image](https://github.com/equinor/webviz/assets/16436291/9500a02a-320b-49cb-b5e1-6dc1d5af94eb)

**Comment by anders-kiaer** [comment]
Agree with most/all of the thinking here. Just to be sure we agree - we here talk about (to a large degree) two independent components.
- One for easy selecting an individual parameter for use in a module _(which I think should be the scope of the issue here)_.
   - Filter based on parameter distribution type.
   - Filter/sort based on parameter group.
   - Sort based on "importance" (definition of "importance" defined by module).
   - Sort based on entropy change (need to compare with "base ensemble").
- One for filtering an ensemble based on parameter values. I might be that such a component want to use the first one.

**Discussion points:**
- What happens when a module have several ensembles and non-equal set of parameters? Intersection or union? Other?
- I think what we talk about here could be an example of a "scalar selector" (other examples: volumetric responses). Define it as such at some point? Could make the "Volumetric plugin" issue easier to solve.

**Comment by jorgenherje** [comment]
Yes, I guess two components:
- One to provide a subset/collection of parameters/names to propagate - e.g. for options in a dropdown.
- One to provide a subset/selection of realization numbers to use

The first one might also provide sorting of the names for further usage

**Comment by jorgenherje** [comment]
First step is resolved by: #405

**Comment by jorgenherje** [comment]
Second step is resolved by: https://github.com/equinor/webviz/pull/741
